### PR TITLE
Streamline for Ackee V2.

### PR DESCRIPTION
**Pull request by BurnedChris**
Hello @WilltheVideoMan.

I saw that you forked it and updated it! 

I have been a bit too busy to do it right now so you rock!  🚀

If would like this to be merged into the plugin I would be happy to give you contributor access :) 

Some parts would need tweaking back and upgrading and I can push the latest version to npm!

### CODE REVIEW

**Comment by willllhallll** [comment]
Hey @Burnsy!

Absolutely, that would be great. Full disclosure, I essentially just combined both yours and @electerious work into this fork, with specific reference to #5, where I have lifted and tweaked the implementation from there. Not much credit is due, honestly! 

Also, just out of personal preference, I removed the Babel transpilation step and just wrote in simple CommonJS-style. Please feel free to revert any of those changes too.

Hope that's all good with you. Cheers!

**Comment by BurnedChris** [comment]
I am happy worth babel transpilation step being removed. Would you be happy to tweaking the readme :)

**Comment by willllhallll** [comment]
Apologies, I will jump on those tweaks this evening. Merge ahoy!

**Comment by willllhallll** [comment]
Hopefully that should all be sorted. I have marked this release v2 since internally `ackee-tracker` v4 no longer supports the old RESTful API. I reckon a major should be required here.

https://github.com/electerious/ackee-tracker/blob/master/CHANGELOG.md#changed-1

Hopefully that is everything! Let me know if there is anything else I can do.

**Comment by BurnedChris** [comment]
i will sort this out later tonight. sorry things tend to get lost in my GitHub notification

**Comment by BurnedChris** [comment]
@WillTheVideoMan  thank you for working on the updates they have been merged!

**Comment by willllhallll** [comment]
Awesome! Great to see it merged. Thanks for the plugin!

**Pull request merged**
